module.exports = {
    SERVICE: 'service',
    PRODUCT: 'product',
    SUPER_ADMIN: 'superAdmin',
    CO_ORDINATOR: 'coOrdinator',
    BUSSINESS:'business',
    FILM:'film',
    FOOD:'food',
    TRAVEL:'travel',
    SOCIALMEDIA_STARS:'Social Media Stars',
    SPORTS:'sports',
    UK:'UK',
    INDIA:'India',
    UAE:'UAE',
    ONE:'1',
    TWO:'2',
    THREE:'3',
    FOUR:'4',
    FIVE:'5',
    NOPREFERENCE:'No Preference' ,
    arrayPosition:[{position:'1'},{position:'2'},{position:'3'},{position:'4'},{position:'5'}]  ,
    PER_PAGE: 10,
    TOPMOST:'top-most',
    TOP:'top',
    LEFT:'left',
    RIGHT:'right',
    CENTER:'center',
    BOTTOM:'bottom',
    adsPosition:[{position:'top-most'},{position:'top'},{position:'left'},{position:'right'},{position:'center'},{position:'bottom'}] 
  };